name: Send QT from 매일성경 - test

on:
  push:
    branches:
        - main
    

jobs:
  send-qt:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
        with:
          repository: myeongjunkim/bansuk-api-bot
          ref: main
      
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Seoul"

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "poetry"
      
      - name: install dependencies
        run: |
          poetry install --sync

      - name: send message
        run: |
          poetry run python scripts/send_message.py \
          --webhook_url=${{ secrets.SLACK_QT_WEBHOOK_URI_TEST }} \
          --google_api_key=${{ secrets.GOOGLE_API_KEY }} \
          --channel_id=${{ secrets.BANSUK_YOUTUBE_CHANNEL_ID }}
        
        